### ISSUE TITLE
Mekanism Extra Compat

### ISSUE THREAD

**Issue by PengyTheGamer** [gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks#11]
originally suggested on curseforge, but making a suggestion here instead

suggestion to add support for this mekanism addon for 1.20.1
https://modrinth.com/mod/mekanism_extra

specifically adding support for the induction cell building
![image](https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/assets/51223619/e1f2f767-435a-42ed-bb8b-93c5b56f3607)

think that's the only thing mekanism extra really adds that can be implemented

**Comment by gisellevonbingen** [comment]
Induction Matrix category in this mod is only calculate inner volume by Induction Matrix dimension. No features else.
'Mekanism Extra' is just add induction matrix's components only.
So nothing to need things to added from this mod.

**Comment by gisellevonbingen** [comment]
Done.
https://legacy.curseforge.com/minecraft/mc-mods/just-enough-mekanism-multiblocks/files/6039603
I'm sorry too late.
