### ISSUE TITLE
[Crash] JEI mixin error with shadow field

### ISSUE THREAD

**Issue by Mysticpasta1** [gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks#12]
https://github.com/mezz/JustEnoughItems/issues/3593 I was told to link this issue for further details

**Comment by gisellevonbingen** [comment]
Ok i will fix it.
Thanks for report.

**Comment by mezz** [comment]
It would be helpful if you can fail gracefully when JEI's code changes. 
Maybe log an error but allow the game to run, that way I don't get a lot of reports for JEI crashing.

I asked around and someone suggested setting this to `0` may help do that:
<https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/blob/60884fc6df039ff13398e21be1e93e45aaca1d84/src/main/resources/jei_mekanism_multiblocks.mixin.client.json#L12>

**Comment by gisellevonbingen** [comment]
Fixed in https://legacy.curseforge.com/minecraft/mc-mods/just-enough-mekanism-multiblocks/files/5537528

**Comment by Mysticpasta1** [comment]
@gisellevonbingen it needs a 1.20.1 version not 1.21 :D

**Comment by Mysticpasta1** [comment]
or at least if it is not marked properly just remark it for 1.20.1

**Comment by gisellevonbingen** [comment]
Ooops XD

**Comment by gisellevonbingen** [comment]
But crashreport is 1.21
Anyway it looks need to fix too.

**Comment by mezz** [comment]
Thank you 🙏  https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/commit/fbc8fdc58d2e1cb96f8732a3cc985d49e84fad54
