### ISSUE TITLE
Crash after the jei update

### ISSUE THREAD

**Issue by SunIAver** [gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks#13]
After updating JEI to jei-1.20.1-forge-15.0.10, the mod does not work. It enters the game and then crashes shortly after.

**Comment by gisellevonbingen** [comment]
Update mod please

**Comment by mezz** [comment]
Duplicate of https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/issues/12
