### ISSUE TITLE
Crash with JEI update 15.8.2.23

### ISSUE THREAD

**Issue by smbarbour** [gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks#14]
Exception reported:
java.lang.NoSuchMethodError: 'mezz.jei.api.gui.IRecipeLayoutDrawable mezz.jei.gui.recipes.RecipeLayoutWithButtons.getRecipeLayout()'

Full crashlog:
https://gist.github.com/smbarbour/4e72035615448cdf57dec4128d2c6dc0

Analysis indicates that mixin will need to be updated.

**Comment by gisellevonbingen** [comment]
Fixed, Try this version: https://legacy.curseforge.com/minecraft/mc-mods/just-enough-mekanism-multiblocks/files/5569679
Thanks for report!

**Comment by Enterprise12nx01** [comment]
> Fixed, Try this version: https://legacy.curseforge.com/minecraft/mc-mods/just-enough-mekanism-multiblocks/files/5569679 Thanks for report!

can you backport this to 1.19 as jei has also done these changes there

**Comment by gisellevonbingen** [comment]
> > Fixed, Try this version: https://legacy.curseforge.com/minecraft/mc-mods/just-enough-mekanism-multiblocks/files/5569679 Thanks for report!
> 
> can you backport this to 1.19 as jei has also done these changes there

Fixed. Thanks for report.

This issue is closed.
Please report as another issue at next.
