### ISSUE TITLE
No longer works with EMI

### ISSUE THREAD

**Issue by MuteTiefling** [gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks#16]
Version 1.21.1-7.1
With older versions of JEI, this was working fine with EMI. I suspect that recent changes in JEI have caused this to break with EMI, however.

As seen below, the viewer is still present, however I'm unable to change any of the values. Clicking the Plus or dragging the bar no longer does anything.

![image](https://github.com/user-attachments/assets/73e5a9f6-e085-46c0-8475-98914c62a2b6)

**Comment by gisellevonbingen** [comment]
EMI is not implement new JEI API yet.
Unfortunately, this mod was developed based on JEI.
So, EMI should implement it for this mod works.
