### ISSUE TITLE
Modrinth latest version crashes

### ISSUE THREAD

**Issue by wExtraBenji** [gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks#18]
The latest version of JEMM on Modrinth is 4.2 which crashes every time I load into a world. I turned only JEMM off and the world loaded just fine.

**Comment by gisellevonbingen** [comment]
Fixed version uploaded. https://modrinth.com/mod/just-enough-mekanism-multiblocks/version/4.5
Thanks for report!
