### ISSUE TITLE
[Question-1.20.1] Is it possible to add support for EMI?

### ISSUE THREAD

**Issue by Gbergz** [gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks#4]
Title ^

Mod in question: https://www.curseforge.com/minecraft/mc-mods/emi

It works and shows etc, but the buttons don't do anything when clicked in EMI.
Probably a longshot but I'll ask anyways.

**-** Gbergz.

**Comment by gisellevonbingen** [comment]
Sorry for late to see.
In my test button clicking was work without problem.
Some UI may be slightly broken or unable to be dragged, but the basic features are fine.

Forge: 47.2.1
JEI: 15.2.0.27
EMI: 1.0.22

![image](https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/assets/44163945/ee195006-598c-47df-8201-544ef1f45a3e)
![image](https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/assets/44163945/14d88d14-c957-4242-bee3-8d6f1f23c56f)

**Comment by Gbergz** [comment]
Now it actually works the second time I tried, maybe the latest EMI update changed something.

It's working atleast!
