### ISSUE TITLE
crash with rei compatibility plugin

### ISSUE THREAD

**Issue by MisileLab** [gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks#9]
my log
https://pastebin.com/GwL7F2Xf

**Comment by gisellevonbingen** [comment]
REI looks doesn't provide needed classes (JEI API)
What is REI version?

**Comment by MisileLab** [comment]
it's 1.20.1 latest version (I dont use rei now so I can't get version now)

**Comment by gisellevonbingen** [comment]
ok i will check
Thanks for report
